import Providers from '@/lib/providers'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" data-theme="light">
			<body className={inter.className}>
				<div className="bg-[url('../public/layoutbg.png')] bg-cover bg-no-repeat min-h-screen" >
					<Header/>
					<main className='max-w-[1200px] m-auto p-5 text-white' >
						<Providers>{children}</Providers>
					</main>
				</div>
			</body>
		</html>
	)
}
